djannet/auth_app/urls.py
from django.urls import path, include

from . import views


app_name = 'auth_app'
urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('register', views.register_user, name='register'),
    path('logout', views.logout_user, name='logout'),
]

djannet/djannet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_app.urls')),
    path('', include('djannet_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djannet/djannet_app/urls.py
from django.urls import path, include

from . import views


app_name = 'djannet_app'
urlpatterns = [
    path('home', views.home_page, name='home'),
]

djannet/djannet_app/models.py
from django.db import models

# Create your models here.

djannet/auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    #creates a form for registering user
    email = forms.EmailField()
    
    class Meta: 
        model = User
        fields = ['username', 'email', 'password1', 'password2']

djannet/auth_app/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout

from .forms import RegisterForm


@csrf_exempt
def register_user(request):
    #view for registering user 
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            
        return redirect("/login")

    else: 
        form = RegisterForm()
        
    return render(request, "auth_app/register.html", {'form': form,})
        
def logout_user(request):
    if request.user.is_authenticated: 
        logout(request)
    return redirect("/home")
        

djannet/djannet_app/views.py
from django.shortcuts import render, redirect


def home_page(request):
    #homepage of the app 
    if request.user.is_authenticated: 
        context = {
            'username' : request.user.username, 
            'email' : request.user.email, 
            'pk' : request.user.pk,
        }
        return render(request, "djannet_app/homepage.html", context)

    return redirect("/login")

djannet/auth_app/templates/auth_app/register.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<h1>Register yourself on Djannet</h1>

<div class="card">
    <div class="card-body">
        <form method="POST" class="form-body">
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-success">Register</button>
        </form>
    </div>
</div>

djannet/djannet_app/templates/djannet_app/homepage.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<nav class="navbar navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand mb-3" href="/home">Djannet</a>

        <form class="form-inline">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <button class="navbar-toggler mb-3" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'auth_app:logout' %}">Sign Out<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item acitve">
                    <a class="nav-link" href="#">Add a new post</a>
                </li>
        </div>
    </div>
</nav>